### ISSUE TITLE
3d point clouds encoder

### ISSUE THREAD

**Issue by zhw-zhang** [liuff19/ReconX#10]
Hi, thank you for your greate work. I am curious, what kind of network is used to encode the 3D point cloud obtained through DUSt3R? Is the PointCloud Encoder a pre-trained transformer model?

**Comment by liuff19** [comment]
For the transformer-based encoder, we encode the DUSt3R point cloud data to a fixed-length sparse representation of the point cloud. Specifically, we first employ a subsampling based on farthest point sampling (FPS) to reduce the point cloud to a smaller set of key points while retaining its overall structural characteristics. Subsequently, cross-attention is applied between the embeddings of the original point cloud and the downsampled point cloud. This mechanism can be interpreted as a form of "partial" self-attention, where the downsampled points act as query anchors that aggregate information from the original point cloud.

The encoder is not initialized from any pretrained models. Instead, it is trained jointly with the video diffusion model in an end-to-end manner. This design choice ensures that the encoder is specifically adapted to the characteristics of DUSt3R point clouds in our experiment datasets.
