### ISSUE TITLE
Question about the point cloud embedder

### ISSUE THREAD

**Issue by ewrfcas** [liuff19/ReconX#5]
Thanks for your good work!
I have some questions about the point cloud embedder shown in Figure2. There is almost no information about the point cloud embedder (Dust3R dose not contain such an embedder for point clouds), and how the point cloud downsampling is accomplished for Eq(10) is also unknown.

**Comment by liuff19** [comment]
The PosEmb implemented in our paper is a column-wise positional embedding function: $\mathbb{R}^3 \rightarrow \mathbb{R}^C$, where $C$ is the dimension of embedding. More specifically, the **PosEmb** function is implemented as follows:

1. **Fixed Sinusoidal Basis**: The basis $\mathbf{e}$ is a 3D sinusoidal encoding: $\mathbf{e} = [\sin(2^0 \pi p), \sin(2^1 \pi p), \dots]$ , where $p \in \mathbb{R}^3$ is the position.
2. **Embedding Calculation**: The input $\mathbf{x}$ is projected onto $\mathbf{e}$ and its sine and cosine are concatenated:
    
     $\mathbf{embeddings} = \text{concat}(\sin(\mathbf{proj}), \cos(\mathbf{proj}))$ 
    
3. **Learnable Transformation**: The positional encoding is passed through an MLP along with the input $\mathbf{x}$: $\mathbf{y} = \text{MLP}(\text{concat}(\mathbf{embeddings}, \mathbf{x}))$
