### ISSUE TITLE
Question about why ReconX chooses DynamiCrafter as the video diffusion backbone?

### ISSUE THREAD

**Issue by wzy-99** [liuff19/ReconX#6]
Hello, @liuff19,

Thanks for your great work!

I have a question about why ReconX  chooses DynamiCrafter as the video diffusion backbone. In fact, there are many alternative video diffusion backbone, such as SVD, open-sore. But why to choose DynamiCrafter as the backbone?

Hope for your answer.

**Comment by liuff19** [comment]
Through our empirical study, we find that DynamiCrafter can achieve better performance in the video interpolation task than other methods.
