### ISSUE TITLE
Details of point clouds

### ISSUE THREAD

**Issue by junyiouy** [liuff19/ReconX#9]
Hi, thanks for the wonderful work. I have a questions about point cloud embedder:

DUSt3R produces point clouds for each pair of images. What is the one that is fed into the point cloud embedder?

**Comment by liuff19** [comment]
For the transformer-based encoder, we encode the DUSt3R point cloud data to a fixed-length sparse representation of the point cloud. Specifically, we first employ a subsampling based on farthest point sampling (FPS) to reduce the point cloud to a smaller set of key points while retaining its overall structural characteristics. Subsequently, cross-attention is applied between the embeddings of the original point cloud and the downsampled point cloud. This mechanism can be interpreted as a form of "partial" self-attention, where the downsampled points act as query anchors that aggregate information from the original point cloud.

The encoder is not initialized from any pretrained models. Instead, it is trained jointly with the video diffusion model in an end-to-end manner. This design choice ensures that the encoder is specifically adapted to the characteristics of DUSt3R point clouds in our experiment datasets.
